// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 27.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'flutter_my_george_game';

  static const String assets_audio_jazzyfrenchy_mp3 = 'assets/audio/jazzyfrenchy.mp3';
  static const String flutter_my_george_game$assets_audio_jazzyfrenchy_mp3 = 'packages/flutter_my_george_game/assets/audio/jazzyfrenchy.mp3';

  static const String assets_audio_littleidea_mp3 = 'assets/audio/littleidea.mp3';
  static const String flutter_my_george_game$assets_audio_littleidea_mp3 = 'packages/flutter_my_george_game/assets/audio/littleidea.mp3';

  static const String assets_audio_music_mp3 = 'assets/audio/music.mp3';
  static const String flutter_my_george_game$assets_audio_music_mp3 = 'packages/flutter_my_george_game/assets/audio/music.mp3';

  static const String assets_audio_smile_mp3 = 'assets/audio/smile.mp3';
  static const String flutter_my_george_game$assets_audio_smile_mp3 = 'packages/flutter_my_george_game/assets/audio/smile.mp3';

  static const String assets_images_Amelia_idle_16x16_png = 'assets/images/Amelia_idle_16x16.png';
  static const String flutter_my_george_game$assets_images_Amelia_idle_16x16_png = 'packages/flutter_my_george_game/assets/images/Amelia_idle_16x16.png';

  static const String assets_images_CutRuby_png = 'assets/images/CutRuby.png';
  static const String flutter_my_george_game$assets_images_CutRuby_png = 'packages/flutter_my_george_game/assets/images/CutRuby.png';

  static const String assets_images_Interiors_free_16x16_png = 'assets/images/Interiors_free_16x16.png';
  static const String flutter_my_george_game$assets_images_Interiors_free_16x16_png = 'packages/flutter_my_george_game/assets/images/Interiors_free_16x16.png';

  static const String assets_images_Serene_Village_16x16_png = 'assets/images/Serene_Village_16x16.png';
  static const String flutter_my_george_game$assets_images_Serene_Village_16x16_png = 'packages/flutter_my_george_game/assets/images/Serene_Village_16x16.png';

  static const String assets_images_apple_pie_png = 'assets/images/apple_pie.png';
  static const String flutter_my_george_game$assets_images_apple_pie_png = 'packages/flutter_my_george_game/assets/images/apple_pie.png';

  static const String assets_images_background_png = 'assets/images/background.png';
  static const String flutter_my_george_game$assets_images_background_png = 'packages/flutter_my_george_game/assets/images/background.png';

  static const String assets_images_background_16x16_png = 'assets/images/background_16x16.png';
  static const String flutter_my_george_game$assets_images_background_16x16_png = 'packages/flutter_my_george_game/assets/images/background_16x16.png';

  static const String assets_images_background_32x32_png = 'assets/images/background_32x32.png';
  static const String flutter_my_george_game$assets_images_background_32x32_png = 'packages/flutter_my_george_game/assets/images/background_32x32.png';

  static const String assets_images_background_48x48_png = 'assets/images/background_48x48.png';
  static const String flutter_my_george_game$assets_images_background_48x48_png = 'packages/flutter_my_george_game/assets/images/background_48x48.png';

  static const String assets_images_baked_goods_json = 'assets/images/baked_goods.json';
  static const String flutter_my_george_game$assets_images_baked_goods_json = 'packages/flutter_my_george_game/assets/images/baked_goods.json';

  static const String assets_images_baked_goods_png = 'assets/images/baked_goods.png';
  static const String flutter_my_george_game$assets_images_baked_goods_png = 'packages/flutter_my_george_game/assets/images/baked_goods.png';

  static const String assets_images_baked_goods_tps = 'assets/images/baked_goods.tps';
  static const String flutter_my_george_game$assets_images_baked_goods_tps = 'packages/flutter_my_george_game/assets/images/baked_goods.tps';

  static const String assets_images_cheesecake_png = 'assets/images/cheesecake.png';
  static const String flutter_my_george_game$assets_images_cheesecake_png = 'packages/flutter_my_george_game/assets/images/cheesecake.png';

  static const String assets_images_choco_cake_png = 'assets/images/choco_cake.png';
  static const String flutter_my_george_game$assets_images_choco_cake_png = 'packages/flutter_my_george_game/assets/images/choco_cake.png';

  static const String assets_images_cookies_png = 'assets/images/cookies.png';
  static const String flutter_my_george_game$assets_images_cookies_png = 'packages/flutter_my_george_game/assets/images/cookies.png';

  static const String assets_images_friend_png = 'assets/images/friend.png';
  static const String flutter_my_george_game$assets_images_friend_png = 'packages/flutter_my_george_game/assets/images/friend.png';

  static const String assets_images_george_png = 'assets/images/george.png';
  static const String flutter_my_george_game$assets_images_george_png = 'packages/flutter_my_george_game/assets/images/george.png';

  static const String assets_images_george2_png = 'assets/images/george2.png';
  static const String flutter_my_george_game$assets_images_george2_png = 'packages/flutter_my_george_game/assets/images/george2.png';

  static const String assets_images_george2_xcf = 'assets/images/george2.xcf';
  static const String flutter_my_george_game$assets_images_george2_xcf = 'packages/flutter_my_george_game/assets/images/george2.xcf';

  static const String assets_images_indoor_png = 'assets/images/indoor.png';
  static const String flutter_my_george_game$assets_images_indoor_png = 'packages/flutter_my_george_game/assets/images/indoor.png';

  static const String assets_images_mossy_cavern_jpg = 'assets/images/mossy_cavern.jpg';
  static const String flutter_my_george_game$assets_images_mossy_cavern_jpg = 'packages/flutter_my_george_game/assets/images/mossy_cavern.jpg';

  static const String assets_images_player_png = 'assets/images/player.png';
  static const String flutter_my_george_game$assets_images_player_png = 'packages/flutter_my_george_game/assets/images/player.png';

  static const String assets_tiles_map_tmx = 'assets/tiles/map.tmx';
  static const String flutter_my_george_game$assets_tiles_map_tmx = 'packages/flutter_my_george_game/assets/tiles/map.tmx';
}
