int direction = 0;
const double animationSpeed = 0.1;
const double characterSize = 100;
const double worldCoordinates = 0.1;
const double characterSpeed = 40;
// const gameWidth = 800.0;
// const gameHeight = 600.0;
const gameWidth = 500.0;
const gameHeight = 800.0;
